CREATE DATABASE ATIVIDADE;
USE ATIVIDADE;

CREATE TABLE PESSOA (
	IRDPESSOA INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45),
    CPF VARCHAR(14),
    DATA_NASCIMENTO VARCHAR(10),
    ENDERECO VARCHAR(45),
    PRIMARY KEY (IRDPESSOA)
);